from aiogram.utils.keyboard import ReplyKeyboardBuilder, InlineKeyboardBuilder

main_keyboard = ReplyKeyboardBuilder()
main_keyboard.button(text='Создать профиль')
main_keyboard.button(text='Изменить профиль')
main_keyboard.button(text='Сменить профиль')
main_keyboard.button(text='Посмотреть вакансии')
main_keyboard.button(text='Получить рекомендации')
main_keyboard.adjust(3, 2)

employment_keyboard = InlineKeyboardBuilder()
employment_keyboard.button(text='Полная', callback_data="Полная")
employment_keyboard.button(text='Частичная', callback_data="Частичная")
employment_keyboard.button(text='Проектная', callback_data="Проектная")
employment_keyboard.button(text='Стажировка', callback_data="Стажировка")
employment_keyboard.button(text='Подработка', callback_data="Подработка")
employment_keyboard.button(text='Неполный день', callback_data="Неполный день")
employment_keyboard.button(text='По выходным', callback_data="По выходным")
employment_keyboard.button(text='По вечерам', callback_data="По вечерам")
employment_keyboard.button(text='Волонтерство', callback_data="Волонтерство")
employment_keyboard.adjust(4)

schedule_keyboard = InlineKeyboardBuilder()
schedule_keyboard.button(text='Полный', callback_data="Полный")
schedule_keyboard.button(text='Сменный', callback_data="Сменный")
schedule_keyboard.button(text='Гибкий', callback_data="Гибкий")
schedule_keyboard.button(text='Удаленная', callback_data="Удаленная")
schedule_keyboard.button(text='Вахта', callback_data="Вахта")
schedule_keyboard.adjust(3)

education_keyboard = InlineKeyboardBuilder()
education_keyboard.button(text='Отсутствует', callback_data="Отсутствует")
education_keyboard.button(text='Среднее профессиональное', callback_data="Среднее профессиональное")
education_keyboard.button(text='Высшее', callback_data="Высшее")
education_keyboard.adjust(1)

experience_keyboard = InlineKeyboardBuilder()
experience_keyboard.button(text='Нет опыта', callback_data="Нет опыта")
experience_keyboard.button(text='1-3 лет', callback_data="1-3 лет")
experience_keyboard.button(text='3-6 лет', callback_data="3-6 лет")
experience_keyboard.button(text='6 лет и более', callback_data="6 лет и более")
experience_keyboard.adjust(2)
